# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [4]:
import numpy as np
data = np.arange(15).reshape(3,5)

print(data)

print('list(a): ', list(a))  #只會把第一層的元素轉換成 List，多層的話只有第一層會轉
print('tolist():', a.tolist()) #才能達成多層的型態轉換

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
# 記得先 Import 正確的套件
import numpy as np

In [10]:
#隨機建出一個包含 6個元素的陣列，元素為 0~9 的整數
a = np.random.randint(10, size=6) 
print(a)

#此陣列是一維陣列
print(a.ndim)

#此一維陣列大小為 6
print(a.shape)

#陣列中有 6個元素
print(a.size)

#陣列中的資料型態為 int32
print(a.dtype)

#陣列中每個元素所占空間
print(a.itemsize)

#陣列長度為 6
print(len(a))

#陣列型態為 numpy.ndarray
print(type(a))

[5 4 9 8 9 5]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [11]:
#隨機出一個 3x4的陣列，元素為 0~9 的整數
b = np.random.randint(10, size=(3,4)) 
print(b)

#此陣列是二維陣列
print(b.ndim)

#此二維陣列大小為 (3,4)
print(b.shape)

#陣列中有 12個元素
print(b.size)

#陣列中的資料型態為 int32
print(b.dtype)

#陣列中每個元素所占空間
print(b.itemsize)

#陣列長度為 3
print(len(b))

#陣列型態為 numpy.ndarray
print(type(b))

[[0 0 9 6]
 [6 4 7 0]
 [2 9 6 8]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [12]:
#隨機出一個 2x3x2的陣列，元素為 0~9 的整數
c = np.random.randint(10, size=(2,3,2)) 
print(c)

#此陣列是三維陣列
print(c.ndim)

#此二維陣列大小為 (2,3,2)
print(c.shape)

#陣列中有 12個元素
print(c.size)

#陣列中的資料型態為 int32
print(c.dtype)

#陣列中每個元素所占空間
print(c.itemsize)

#陣列長度為 2
print(len(c))

#陣列型態為 numpy.ndarray
print(type(c))

[[[0 6]
  [3 3]
  [7 9]]

 [[2 7]
  [9 9]
  [9 2]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [13]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[3, 6, 0, 5, 7, 9]
[3, 6, 0, 5, 7, 9]


In [14]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[7, 6, 8, 2], [0, 3, 9, 9], [1, 9, 6, 3]]
[array([7, 6, 8, 2]), array([0, 3, 9, 9]), array([1, 9, 6, 3])]


In [15]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 2], [0, 5], [9, 7]], [[7, 0], [2, 9], [7, 4]]]
[array([[2, 2],
       [0, 5],
       [9, 7]]), array([[7, 0],
       [2, 9],
       [7, 4]])]


In [21]:
def list(iterable):
    return iterable.tolist()

print('list(a) -> a.tolist:', list(a))
print('list(b) -> b.tolist:', list(b))
print('list(c) -> c.tolist:', list(c))

list(a) -> a.tolist: [3, 6, 0, 5, 7, 9]
list(b) -> b.tolist: [[7, 6, 8, 2], [0, 3, 9, 9], [1, 9, 6, 3]]
list(c) -> c.tolist: [[[2, 2], [0, 5], [9, 7]], [[7, 0], [2, 9], [7, 4]]]


### 延伸題
題目: 1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。 2.呈上題，將以上數列取出偶數。 3.呈1題，將數列取出3的倍數。

In [23]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
x = np.arange(21)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [26]:
#2.呈上題，將以上數列取出偶數。
y = np.arange(2,21,2)
print(y)

[ 2  4  6  8 10 12 14 16 18 20]


In [27]:
#3.呈1題，將數列取出3的倍數。
z = np.arange(3,21,3)
print(z)

[ 3  6  9 12 15 18]
