# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [36]:
# 記得先 Import 正確的套件
import numpy as np

a = np.arange(1,12)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11]


In [39]:
a[(a>=3) & (a<=6)] *= -1

print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [40]:
A = np.random.rand(3, 6)
print(A)

[[0.1763588  0.37658257 0.21947649 0.45153852 0.1646693  0.84532038]
 [0.56161929 0.42606695 0.94907718 0.01786055 0.96331164 0.00135158]
 [0.58676646 0.15507088 0.9628103  0.7978149  0.80762426 0.89900017]]


In [46]:
B = A[A>0.5]

print(B)
B.size

[0.84532038 0.56161929 0.94907718 0.96331164 0.58676646 0.9628103
 0.7978149  0.80762426 0.89900017]


9