# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [8]:
import numpy as np

a = np.arange(8).reshape(2,4)
print(a)

#以下兩者出來的結果都一樣，都是整個陣列元素的總合
print(a.sum())
print(np.sum(a))

#下面第三種會回傳 axis=0的總合
print(sum(a))

[[0 1 2 3]
 [4 5 6 7]]
28
28
[ 4  6  8 10]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [9]:
# 記得先 Import 正確的套件

import numpy as np

#資料的正規化(Normalization)是將原始資料的數據按比例縮放於 [0, 1] 區間中，且不改變其原本分佈。

In [16]:
A = np.random.random((5, 5))
print(A)

normalA = (A-A.min())/(A.max()-A.min())

print('After normalization: ')
print(normalA)

[[0.65437974 0.96791433 0.14394524 0.4367629  0.81184503]
 [0.70665296 0.82368111 0.24806418 0.17278688 0.23711488]
 [0.1751707  0.08486247 0.83289917 0.00566821 0.20224428]
 [0.53560367 0.13873592 0.06276842 0.95478885 0.23329578]
 [0.52816375 0.73671583 0.39050448 0.37123391 0.55907807]]
After normalization: 
[[0.67416383 1.         0.14370235 0.44800876 0.83780729]
 [0.728488   0.85010776 0.25190641 0.17367559 0.24052751]
 [0.17615295 0.08230147 0.85968749 0.         0.20428876]
 [0.55072756 0.13828864 0.05934055 0.98635954 0.23655857]
 [0.54299574 0.75973039 0.39993538 0.37990872 0.57512299]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [19]:
import numpy as np

b = np.random.randint(0,100,10)
print('Original data: ')
print(b)

b[b.argmax()] = -1
print('Update data: ')
print(b)

Original data: 
[89 33 23 11 89 97 48 52 15 35]
Update data: 
[89 33 23 11 89 -1 48 52 15 35]
